### ISSUE TITLE
General programming session ideas

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#18]
It's great to talk about programming challenges in specific fields, but there are also tools and skills that are universally useful to scientific programmers. List your session ideas here for non-subject-specific programming things (like debugging or unit testing). 

We'll also be able to populate this issue with suggestions from our [second coworking session] in three weeks, (https://github.com/UofTCoders/Events/issues/2), the theme of which is 'Life's great programming challenges'.

**Comment by adunning** [comment]
Thanks for organizing this! If you want me to do sessions on Pandoc, citation tools, or web design (I would probably suggest looking at Jekyll/GitHub Pages as a simple intro to HTML and CSS), I am quite game.

**Comment by lannajin** [comment]
Oh shoot, posted this request below in possibly the wrong thread. Sorry, not savvy at GitHub, but:
Thanks for organizing the session today! Can I also recommend we create a calendar that can be imported into Google calendar or whatever people use (iCal?) to keep track of events?

**Comment by lannajin** [comment]
On that note, is it possible to create a git compatible calendar? So for example if someone wants to present something on one date, they could tentatively add it on the calendar for then the admin to approve or reject?

**Comment by mbonsma** [comment]
I really like the calendar idea! We could make a public Google calendar for sure, but I don't know about Git compatibility. Anyone else know about this stuff? We could always just make it in Google and then include a link to the calendar on the website / repo. 

I'll make a thread for the calendar idea.

**Comment by mbonsma** [comment]
@adunning: I'm adding a few session proposals to the [wiki](https://github.com/UofTCoders/studyGroup/wiki/Session-Proposals) - feel free to add dates that you could do those sessions. I'll also add some of the other things we talked about to this thread.

**Comment by mbonsma** [comment]
Another session on **version control and workflow management** (like "philosophy of Git" - why should you use it, what can you get out of it) would be great. On Thursday we talked about doing this session sometime in September to coincide with the beginning of another school year.

**Comment by mbonsma** [comment]
A session on [D3](http://d3js.org/) would be applicable to people across many disciplines. I'm not familiar with D3, but I think it has something to do with putting data in a form that can be interactive and shareable, like plots that you can share over the web and stuff. @aerler mentioned there might be someone in his group who could lead a D3 session. Also @ricardoharripaul - would you be willing to teach D3?

**Comment by mbonsma** [comment]
[LaTeX](http://www.latex-project.org/) - endlessly useful for anyone who has to make documents ever. Maybe we could do a split code-along / discussion session on LaTeX - part intro to how it works, and then we could discuss related tools people use (editors, templates, etc). Apparently there's a template for a UofT thesis!

**Comment by mbonsma** [comment]
General idea: we could have **themed coworking sessions** - things like plotting, or data I/O, etc. We could all bring something we're working on within that theme, and then questions and discussion would focus on that.

**Comment by mbonsma** [comment]
**Citation managers** - Endnote, Zotero, Mendeley, etc. Should this be a roundtable discussion? A series of lightning demos? A work-along?

**Comment by mbonsma** [comment]
Best practices / software carpentry / outside teachers - we could have follow-up sessions to [software carpentry](https://software-carpentry.org/) workshops to learn some best practices. Or we could teach our own sessions using [software carpentry materials](https://software-carpentry.org/lessons.html) - this would be a good way for us to practice teaching as well as get some quality lesson materials.

**Comment by mbonsma** [comment]
APIs - how to get data off the web.

**Comment by mbonsma** [comment]
Last one from Thursday - ways to stitch Python and R together? @aerler mentioned that it's possible to use them together, and it would be cool to learn more about that, especially since a lot of people in the group use either R or Python.

**Comment by smales** [comment]
What about Databases? More specifically, I am interested in applying some kind of database to organize the experimental data that we collect while maintaining a link to the experiment settings during those measurements. This could also apply to simulation results instead of experimental measurements. I'm sure there are other ways use of databases could make our lives easier as well.

**Comment by QuLogic** [comment]
In any particular language? Or just [SQL](https://en.wikipedia.org/wiki/SQL) in general?

A full database might be overkill, but something lightweight like sqlite might work.

Though in your example, you might want to convert the datasets to HDF5 and start storing experiment settings as attributes in the file itself. It sort of depends on what sort of processing you want to do with it.

**Comment by aerler** [comment]
I'd definitely second that! I would be particularly interested in Python tools for databases, because I find the current SQL API in Python quite awkward to use.

Also, I think I know what @smales is thinking of - I thought about it myself. I would definitely store attributes with the data in HDF5/NetCDF4, but I often want to select a few experiments based on criteria and I don't want to parse all the big data files for that. Having parameters and attributes stored in a database would be extremely useful (and you could build the database from the HDF5/NetCDF4 files).

**Comment by smales** [comment]
In terms of session proposals it might be nice to have one where many different types of databases/languages are presented with pros and cons of each. It might also be interesting to have a session where people simply describe how they are using a database in their research and why they are using that one. Even if ultimately unrelated to to my immediate research, I am curious about database software as it is something that I don't have a lot of familiarity with.

I think @aerler and I are thinking very similarly. I should think a bit more about exactly what I want to accomplish with implementing a database beyond the following points:
- It would be useful to be able to query a database for experimental values in analysis code instead of typing them in by hand.
- As @aerler said, It would also be very useful to be able to select data runs over a range of time based on a set of criteria.
- It would be useful to be able to easily query and relate e.g. the temperature in the lab, to the results of some analysis of the data. This implies that, at least a subset of, the results of analysis done on the data is in a database.

I am also not sure that the effort required to do this is worth it. But maybe talking with people will make this easier. I should note that the current way of doing things in our lab works, this would be an improvement.

**Comment by QuLogic** [comment]
In Python land, I'd say Pandas might be the way to go for that sort of thing. It's not going to be a full relational database, but I suspect that most metadata wouldn't require it. Assuming I haven't misinterpreted anything, it should be able to do many/all of those points. It has several backends, so you could have it backed by sqlite or HDF5 (which might make it easier to update the result from some other language.) And the API is modelled in some ways after R, but more Pythonic.

We could maybe have a multi-language work-along with R and Pandas. I'm not what you'd call an expert in Pandas, but I was able to figure out most of @lwjohnst86's R talk using Pandas on Thursday after learning how to do a few small things.

**Comment by aerler** [comment]
Pandas+SQL backend sounds like an interesting option.
I would also like a session were people just show how they are using databases.
Like @smales I'm also evaluating whether I can use databases in a fruitful way in my (future) research.

**Comment by mbonsma** [comment]
I like the databases discussion session idea. I'm curious what's out there, I'll add my vote to @smales and @aerler for that. This sounds like it would make a good coding lightning demo - 5-10 minutes per presenter for a bunch of different databases/configurations. @QuLogic, would you be okay with being a Pandas presenter? 

Is there anyone else out there who uses a database and would be interested in very briefly presenting on what they use and why?

**Comment by linamnt** [comment]
I use databases with sqlite through python, I'm by no means an expert, but
I can show how I use it for my purposes?

On Tue, Jul 28, 2015 at 10:42 AM, mbonsma notifications@github.com wrote:

> I like the databases discussion session idea. I'm curious what's out
> there, I'll add my vote to @smales https://github.com/smales and @aerler
> https://github.com/aerler for that. This sounds like it would make a
> good coding lightning demo - 5-10 minutes per presenter for a bunch of
> different databases/configurations. @QuLogic https://github.com/QuLogic,
> would you be okay with being a Pandas presenter?
> 
> Is there anyone else out there who uses a database and would be interested
> in very briefly presenting on what they use and why?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UofTCoders/studyGroup/issues/18#issuecomment-125633116
> .

## 

Lina Tran
MSc. Candidate | Frankland Lab
Department of Physiology
University of Toronto

**Comment by mbonsma** [comment]
@linamnt that would be fantastic!

**Comment by lwjohnst86** [comment]
Most of these ideas and adding them to the schedule has been moved to the [wiki](https://github.com/UofTCoders/studyGroup/wiki) or has been developed into a survey. Future suggests can [create a new issue](https://github.com/UofTCoders/studyGroup/issues/new)
