### ISSUE TITLE
Session ideas for Winter 2017

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#214]
The last survey we did was in April 2016, so we should probably do another soon. But in the meantime, so we can plan the first few weeks of next term, here are some ideas based on previous survey results:

* Intro Git
* Advanced topics in Git
* Code review and/or pair programming - possibly bring someone in to teach us code review
* Open data - Mozilla Science Lab is developing some [great material](https://github.com/mozillascience/open-data-training) on this.
* More lightning demos? Any theme ideas?

**Comment by joelostblom** [comment]
If there is interest, I can have a lightning demo or presentation on zsh, tmux, and/or vim (for scholarly markdown rather than coding) together. I am not an expert in these, but I use them daily and can show why I think they are fun and useful.

I am leaning towards a lightning demo just because I believe it will be cumbersome to provide instructions on how to set them up across platforms, and it might require some time to customize the setups... But I can look into what a minimal install would look like.

On another note, I think the group project #97 is a cool idea and would be interested in participating in that! Potentially together with another group, such as the new ML one, if more manpower is needed?

**Comment by linamnt** [comment]
@joelostblom  That would be super cool for a presentation I think!

Also for the group project, http://kaggle.com/ has a lot of cool datasets as well as big data competitions/challenges (mainly ML based so a collaboration with the ML club could be cool) and functionality to contribute code in different languages towards the challenge. Maybe we can check it out?

**Comment by lwjohnst86** [comment]
@joelostblom I would also be up for giving a quick demo on i3 (window manager using vim key bindings) to smoother workflow. It is also a loooot of fun to use. And I think it fits with your idea of tmux/vim/zsh etc.

**Comment by joelostblom** [comment]
@linamnt Kaggle sounds like fun! I think I would have an additional 1 or 2 of my colleagues interested in joining for that!

@lwjohnst86 I dabbled around in i3 some while back, but ended up just stealing some of the shortcuts and behavior I liked into my Gnome setup. Would be cool to see how you use it!

**Comment by linamnt** [comment]
I also really like the idea of a code review session + bringing in someone to teach us!

I could also teach a 'Network Analysis in Python with NetworkX' lesson with a focus on social networks, (maybe a brief mention on brain networks too).

**Comment by derekhoward** [comment]
I like all these ideas so far!

@mbonsma I really like the idea of using the Mozilla open data materials. There are some more guides I've found interesting which may be useful from the [Open Data institute](http://theodi.org/guides).
Also, [Propublica](https://github.com/propublica/guides/blob/master/data-bulletproofing.md) and [Quartz ](https://github.com/Quartz/bad-data-guide) magazines have both compiled some useful info on data cleaning, pitfalls and common mistakes to avoid.

Also, for lightning demos I think it would be interesting to showcase different data cleaning techniques/useful libraries. I've found that's an essential step in actually making use of open government data since it isn't always in the best shape for use.

One specific library I've repeatedly found useful is [FuzzyWuzzy](https://github.com/seatgeek/fuzzywuzzy) for fuzzy string matching. It's allowed me to join different datasets on keys that don't identically match due to various formatting/spelling differences.

**Comment by linamnt** [comment]
Too late for Winter 2017, but I was thinking it might be cool to have a lesson on using Python as a replacement for shell scripting or in conjunction with commandline, it could go over subprocess, argparse/getopt or other relevant packages... (+ cool new Fire package by Google)

Also I like the idea of a lesson just on data cleaning techniques as per Derek's post. I feel there's a lot there potentially and highly relevant to grad students who might inherit a lot of wonky datasets (or generate their own too of course!).

**Comment by joelostblom** [comment]
Sounds like fun!
I actually tried running ipython as my system shell for a while, but
stopped when due to its less than ideal piping and tab completion... it it
makes much more sense for scripting.
