### ISSUE TITLE
Seeking Coder to Be CTO for Ed-Tech Company 

### ISSUE THREAD

**Issue by MattStodolak** [UofTCoders/studyGroup#339]
Hello all,

I am completing my Master of Teaching at U of T where my research has focused on the integration of technology with education and seeking to create a suite of apps using game-based learning and gamification pedagogy. If you are interested, please do not hesitate to get in contact. I'm working on UX right now with a designer. Email: matthew.stodolak@gmail.com

Best,

Matthew Stodolak

**Comment by mbonsma** [comment]
Hi @MattStodolak, this sounds really cool! If you're interested, we'd love to have you come and talk to the group sometime about your work. 

Another group of people who would be really interested in hearing what you're up to would be the [Teaching Tech Together meetup](http://third-bit.com/2018/01/03/t3toronto-meetup-jan-2018.html). They've been happening monthly since October, and I don't think the February one is scheduled yet but @gvwilson is the person to talk to for more info about that.

**Comment by MattStodolak** [comment]
Hello Madeleine,

Thank you for your response! I really appreciate it, and the other contacts you suggested I get in touch with. I’d be happy to come and talk to your group and share my vision. Do you have a meeting coming up that I could attend?

Best Wishes,

Matthew Stodolak

**Comment by mbonsma** [comment]
Hi @MattStodolak, we meet every Thursday at 6 pm in the MADLab at Gerstein Library. You'd be welcome to come at 6 and share a brief pitch before the weekly event starts at 6:10!

**Comment by joelostblom** [comment]
@MattStodolak Please reopen if you are still looking for help with this
