### ISSUE TITLE
Group leadership structure changes

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#78]
As this group grows and evolves, it might be a good idea to have a formal leadership structure. Nothing has been decided yet, so this is just to test the waters and get some feedback. 

Some reasons we might want an executive committee:
- the leadership, organizing, and improvement of the group is distributed among multiple people
- there is continuity in the group as people arrive and leave, it doesn't require the same people to be there forever
- the people who have already been heavily involved in leadership are formally recognized

These are some possible roles:
- President: leadership and vision, recruitment, Mozilla liaison
- Secretary: update website with events, send reminder emails, book rooms
- Technical Manager: manage and monitor Github repo site etc. (multiple?) 
- Content manager / developer: improve website and/or group structure, keep in touch with Mozilla-suggested improvements
- Treasurer - snack buyer, keeping track of receipts

**Questions for you:**
- Should we hold an election? (Should it be soon, or in April, which is when they would happen every year going forward?)
- Any comments - what roles should there be, who should fill them, should we do something entirely different, etc. 

If you'd like to give anonymous comments, head on over to this [form](https://docs.google.com/forms/d/1d8Zv9XVrxwDG3K4SAakVWzj2OkKigx3nO-wI9X_Le2M/viewform?usp=send_form).

**Comment by lwjohnst86** [comment]
I think April is a good time to start elections. Otherwise we would be off cycle from other groups. Not that that is wrong or anything.. Only issue is that is four months away. Do we want to get this going sooner?

I like the roles so far, tho not entirely sure what the difference is between CM/dev and technical manager. I assume the technical manager would deal with setting up and dealing with Issues?

As I mentioned before, I am the treasurer for my grad association, so being treasurer here would be fairly easy for me.

**Comment by mbonsma** [comment]
I tentatively stuck an election on April 21 at the usual time. I agree, April is good. We could have interim roles in the meantime? 

CM and TM could be the same person, for sure.

**Comment by lwjohnst86** [comment]
Election has been set [here](https://github.com/UofTCoders/studyGroup/issues/112) and a council [repo](https://github.com/UofTCoders/council) has been set up too.
