### ISSUE TITLE
Importing Packages/Modules Within Class Definitions

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/studyGroup#90]
Yesterday, there was a question about being able to import a module/package within a class assuming you would need certain functions from that package in your class methods. 

I wasn't too sure about the procedure and suggested doing all imports at the top of the script as you normally would, but Derek directed me to this: http://stackoverflow.com/questions/6883319/python-use-an-import-done-inside-of-a-class-in-a-function which has very helpful tips and explanations for how you can make it work! 

What I gleaned from it is that while it is easier to import at the top-level outside your class definition, there are definitely ways to do it if you want to keep the module functions contained within the class that is using the functions.

**Comment by QuLogic** [comment]
That is an interesting post, but it's a bit of a niche usage, I think. That is, the post shows how to import a function from a module and make it into a static method in the class. Your description is slightly different; importing the function so that they're available _in_ the methods only. That could be done with a regular import contained within the method.

The advantage of importing within the class method is that the dependency remains optional until the specific method is used.

**Comment by linamnt** [comment]
Good points! Thanks for the distinction Elliott!
