### ISSUE TITLE
Possible group project

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#97]
It would be cool to have a project we could work on as a group on a semi-ongoing basis. We could build new tools or analysis around open datasets, for example. This was suggested by [Birgit Fleischmann](https://twitter.com/efelei). 

**Benefits:**
- Meaningful and interesting examples for coworking sessions and code-alongs
- Project development skills - participants can point to contributions on their resumes
- Practicing open science
- Fun!

**Possible datasets:**
- [Open data from the City of Toronto](http://www1.toronto.ca/wps/portal/contentonly?vgnextoid=9e56e03bb8d1e310VgnVCM10000071d60f89RCRD) - building shapes across Toronto? Bicycle counts?
- Anything from [namaria](https://namara.io/#/) - an open data repository with stuff from all over Canada and the US. Toronto red light cameras? Environment Canada climate data? 

**Suggest your own ideas or thoughts in the comments!**

**Comment by linamnt** [comment]
I think this is definitely a good idea for pretty much all those reasons you listed :)

I was thinking the other day about how it'd be cool if there were an app that would tell you where the nearby bike posts/rings are when you search up a location. May not be so useful because it's not that hard to look around on your way to your destination and look for a place to put your bike but it could become a way for people to indicate regions they would like more posts (e.g. if they exist but are always full, none in a region that needs it etc.) since [Toronto takes suggestions](http://www1.toronto.ca/wps/portal/contentonly?vgnextoid=6735970aa08c1410VgnVCM10000071d60f89RCRD) and if it's backed up with real data, they might be more inclined to agree. Namara.io has a [dataset](https://namara.io/#/data_sets/b5d9a990-246a-4a40-beaa-bb92a8132ce7) though incomplete. could be a starting point.

The only app that I found is [this](https://itunes.apple.com/ca/app/bike-rack-locator/id584144552?mt=8) but not available in Toronto, let me know if there is one that I haven't found.

Anyway, could be a fun project? or not! just an idea!

**Comment by QuLogic** [comment]
Toronto has [that open dataset](http://www1.toronto.ca/wps/portal/contentonly?vgnextoid=d46e94ec9fbf3310VgnVCM1000003dd60f89RCRD&vgnextchannel=1a66e03bb8d1e310VgnVCM10000071d60f89RCRD), but for some reason, it's not visible on [their Open Data map](http://map.toronto.ca/maps/map.jsp?app=OpenData).

**Comment by mbonsma** [comment]
@linamnt that's a great idea! And the fact that it already exists but not for Toronto means that there could be demand for it.

**Comment by lwjohnst86** [comment]
I also like this idea. Would be nice to see group collaboration in 'real-time' :stuck_out_tongue_winking_eye: Tho, what you are suggesting @linamnt seems more likely a python or some other project than R... I'm not aware of apps that use R, haha. Could be wrong tho.

**Comment by linamnt** [comment]
It's all kind of a nebulous idea in my mind at this point, but I think there is certainly room for R users (and people of all sorts of programming languages!) to contribute. Especially since it doesn't really have to be a phone app so much as something easily accessible and interactive that would work with the coordinates and render them on a map (and hopefully with some swanky features). For example, I don't really know the extent of what Shiny can do, but I _think_ it could be implemented in that as well.

**Comment by mbonsma** [comment]
Or we could have TWO projects on the go, one for the Python enthusiasts, one for the R enthusiasts. 

Also, there's a group in the UK holding some R hackathons using some cool wildlife data. I asked them to let us know the details, because they're opening it up for remote participants. I'll update when I hear from them!

**Comment by dcwalk** [comment]
Just a thought -- if you are interested in an open data project the [civictech.ca](http://civictech.ca/) group might be good to connect with. They meet every Tuesday! They have a few projects starting up that are on github: [CivicTechTO](https://github.com/CivicTechTO)

**Comment by mbonsma** [comment]
Another thing Birgit sent me: http://wiki.opendataday.org/Main_Page, a Toronto event will be hosted by Civic Tech TO!
